<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 30 Produk Technology untuk seller_id = 1
        $techProducts = [
            [
                'seller_id' => 1,
                'name' => 'Gaming Laptop RTX 4060 16GB RAM 512GB SSD',
                'description' => 'Laptop gaming dengan prosesor Intel Core i7 Gen 13, RTX 4060 8GB, RAM 16GB DDR5, layar 15.6" 144Hz',
                'price' => 15999000,
                'original_price' => 18999000,
                'stock' => 15,
                'image_url' => 'https://placehold.co/400x400/1A1A1A/00FF00?text=Gaming+Laptop',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 45,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 16,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'iPhone 15 Pro Max 256GB Titanium Blue',
                'description' => 'iPhone terbaru dengan chip A17 Pro, kamera 48MP, USB-C, garansi resmi iBox 1 tahun',
                'price' => 21999000,
                'original_price' => 22999000,
                'stock' => 25,
                'image_url' => 'https://placehold.co/400x400/0066CC/FFFFFF?text=iPhone+15',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 78,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 4,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Samsung Galaxy S24 Ultra 12GB/512GB',
                'description' => 'Flagship Samsung dengan S Pen, Snapdragon 8 Gen 3, kamera 200MP, layar AMOLED 6.8"',
                'price' => 18499000,
                'original_price' => 19999000,
                'stock' => 30,
                'image_url' => 'https://placehold.co/400x400/000000/FFFFFF?text=Galaxy+S24',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 92,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 8,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'MacBook Air M3 8GB 256GB Space Gray 2024',
                'description' => 'MacBook Air dengan chip M3 terbaru, layar Liquid Retina 13.6", battery life hingga 18 jam',
                'price' => 17999000,
                'original_price' => 18999000,
                'stock' => 20,
                'image_url' => 'https://placehold.co/400x400/2C2C2C/FFFFFF?text=MacBook+Air',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 65,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 5,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Sony WH-1000XM5 Wireless Noise Cancelling',
                'description' => 'Headphone premium dengan ANC terbaik, audio Hi-Res, battery 30 jam, multipoint connection',
                'price' => 4999000,
                'original_price' => 5999000,
                'stock' => 50,
                'image_url' => 'https://placehold.co/400x400/FFD700/000000?text=Sony+WH1000XM5',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 156,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 17,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'iPad Pro M2 11" 128GB WiFi Space Gray',
                'description' => 'iPad Pro dengan chip M2, layar Liquid Retina 11", support Apple Pencil Gen 2',
                'price' => 13999000,
                'original_price' => 14999000,
                'stock' => 18,
                'image_url' => 'https://placehold.co/400x400/333333/FFFFFF?text=iPad+Pro',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 48,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 7,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'ASUS ROG Zephyrus G14 Ryzen 9 RTX 4070',
                'description' => 'Gaming laptop compact dengan AMD Ryzen 9 7940HS, RTX 4070 8GB, RAM 32GB, layar QHD+ 165Hz',
                'price' => 24999000,
                'original_price' => 27999000,
                'stock' => 10,
                'image_url' => 'https://placehold.co/400x400/FF0000/FFFFFF?text=ROG+G14',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 28,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 11,
                'badge' => 'Ekslusif',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Apple Watch Series 9 GPS 45mm Midnight',
                'description' => 'Smartwatch dengan chip S9, Always-On Retina display, health monitoring lengkap',
                'price' => 7999000,
                'original_price' => 8499000,
                'stock' => 35,
                'image_url' => 'https://placehold.co/400x400/000033/FFFFFF?text=Watch+S9',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 112,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 6,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Samsung Galaxy Tab S9+ 12GB/256GB',
                'description' => 'Tablet premium dengan Snapdragon 8 Gen 2, layar AMOLED 12.4", S Pen included',
                'price' => 12999000,
                'original_price' => 14499000,
                'stock' => 22,
                'image_url' => 'https://placehold.co/400x400/1A1A2E/FFFFFF?text=Tab+S9',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 58,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 10,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Logitech MX Master 3S Wireless Mouse',
                'description' => 'Mouse ergonomis premium dengan sensor 8K DPI, multi-device, silent click',
                'price' => 1499000,
                'original_price' => 1799000,
                'stock' => 60,
                'image_url' => 'https://placehold.co/400x400/4A4A4A/FFFFFF?text=MX+Master',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 245,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 17,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Keychron K8 Pro Mechanical Keyboard Wireless',
                'description' => 'Mechanical keyboard wireless hot-swappable, RGB backlight, Gateron switch',
                'price' => 1899000,
                'original_price' => 2199000,
                'stock' => 45,
                'image_url' => 'https://placehold.co/400x400/2D2D2D/00FF00?text=Keychron+K8',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 187,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 14,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Dell UltraSharp 27" 4K USB-C Monitor',
                'description' => 'Monitor 4K IPS dengan USB-C 90W power delivery, color accuracy 99% sRGB',
                'price' => 8999000,
                'original_price' => 9999000,
                'stock' => 15,
                'image_url' => 'https://placehold.co/400x400/0078D7/FFFFFF?text=Dell+Monitor',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 76,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 10,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Sony Alpha A7 IV Mirrorless Camera Body',
                'description' => 'Kamera mirrorless full-frame 33MP, 4K 60fps, in-body stabilization 5.5 stop',
                'price' => 34999000,
                'original_price' => 36999000,
                'stock' => 8,
                'image_url' => 'https://placehold.co/400x400/000000/FFFFFF?text=Sony+A7IV',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 32,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 5,
                'badge' => 'Ekslusif',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'DJI Mini 4 Pro Drone with RC 2',
                'description' => 'Drone compact dengan sensor 1/1.3", video 4K HDR 60fps, obstacle sensing omnidirectional',
                'price' => 12999000,
                'original_price' => 13999000,
                'stock' => 12,
                'image_url' => 'https://placehold.co/400x400/555555/FFFFFF?text=DJI+Mini4',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 41,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 7,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'GoPro HERO 12 Black Action Camera',
                'description' => 'Action camera 5.3K 60fps, HyperSmooth 6.0, waterproof 10m, HDR video',
                'price' => 6999000,
                'original_price' => 7499000,
                'stock' => 28,
                'image_url' => 'https://placehold.co/400x400/00A3E0/000000?text=GoPro+12',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 95,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 7,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Bose QuietComfort 45 Wireless Headphones',
                'description' => 'Headphone ANC dengan kualitas audio premium, battery 24 jam, comfortable fit',
                'price' => 4299000,
                'original_price' => 4999000,
                'stock' => 42,
                'image_url' => 'https://placehold.co/400x400/1A1A1A/FFFFFF?text=Bose+QC45',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 134,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 14,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Razer DeathAdder V3 Pro Wireless Gaming Mouse',
                'description' => 'Gaming mouse dengan sensor Focus Pro 30K, 90 jam battery life, ultra-lightweight 63g',
                'price' => 2199000,
                'original_price' => 2499000,
                'stock' => 55,
                'image_url' => 'https://placehold.co/400x400/00FF00/000000?text=Razer+Mouse',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 167,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 12,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'SanDisk Extreme Pro 1TB Portable SSD USB 3.2',
                'description' => 'SSD portable dengan kecepatan read 2000MB/s, IP55 water/dust resistant',
                'price' => 2499000,
                'original_price' => 2899000,
                'stock' => 65,
                'image_url' => 'https://placehold.co/400x400/FF6600/000000?text=SanDisk+SSD',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 198,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 14,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'LG UltraGear 34" Curved Gaming Monitor 144Hz',
                'description' => 'Monitor gaming curved 34" WQHD, 144Hz, 1ms response, HDR10, G-Sync compatible',
                'price' => 7499000,
                'original_price' => 8499000,
                'stock' => 14,
                'image_url' => 'https://placehold.co/400x400/A50034/FFFFFF?text=LG+UltraGear',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 68,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 12,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Xiaomi Mi Band 8 Pro Smart Band GPS',
                'description' => 'Smart band dengan GPS built-in, layar AMOLED 1.74", 150+ workout modes, battery 14 hari',
                'price' => 799000,
                'original_price' => 999000,
                'stock' => 120,
                'image_url' => 'https://placehold.co/400x400/FF6900/FFFFFF?text=Mi+Band+8',
                'category' => 'Technology',
                'rating' => 4,
                'sold_count' => 312,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 20,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Anker PowerCore 20000mAh USB-C PD 65W',
                'description' => 'Power bank fast charging 65W dengan USB-C PD, dapat charge laptop, LED display',
                'price' => 899000,
                'original_price' => 1099000,
                'stock' => 85,
                'image_url' => 'https://placehold.co/400x400/00A3FF/FFFFFF?text=Anker+20K',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 278,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 18,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'TP-Link Archer AX73 WiFi 6 Router AX5400',
                'description' => 'WiFi 6 router dual-band 5400Mbps, 6 antena high-gain, OFDMA, MU-MIMO',
                'price' => 1399000,
                'original_price' => 1699000,
                'stock' => 48,
                'image_url' => 'https://placehold.co/400x400/00B8D4/FFFFFF?text=TP+Link',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 156,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 18,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Corsair Vengeance RGB 32GB (2x16GB) DDR5 6000MHz',
                'description' => 'RAM DDR5 high-performance dengan RGB lighting, optimized for Intel/AMD platform',
                'price' => 2899000,
                'original_price' => 3299000,
                'stock' => 38,
                'image_url' => 'https://placehold.co/400x400/FFCC00/000000?text=Corsair+RAM',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 145,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 12,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Western Digital Black SN850X 2TB NVMe Gen4',
                'description' => 'SSD NVMe Gen4 dengan read speed 7300MB/s, heatsink included, 5 tahun garansi',
                'price' => 3999000,
                'original_price' => 4499000,
                'stock' => 32,
                'image_url' => 'https://placehold.co/400x400/000000/00A3E0?text=WD+Black',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 98,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 11,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'NVIDIA GeForce RTX 4070 Ti 12GB GDDR6X',
                'description' => 'Graphics card RTX 4070 Ti dengan DLSS 3, Ray Tracing Gen 3, cooling system advanced',
                'price' => 14999000,
                'original_price' => 15999000,
                'stock' => 10,
                'image_url' => 'https://placehold.co/400x400/76B900/000000?text=RTX+4070Ti',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 52,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 6,
                'badge' => 'Ekslusif',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'HyperX Cloud Alpha Wireless Gaming Headset',
                'description' => 'Gaming headset wireless dengan battery 300 jam, DTS Headphone:X, detachable mic',
                'price' => 2799000,
                'original_price' => 3199000,
                'stock' => 44,
                'image_url' => 'https://placehold.co/400x400/E60012/000000?text=HyperX+Alpha',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 124,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 13,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Elgato Stream Deck MK.2 15 Keys',
                'description' => 'Stream control panel dengan 15 LCD keys, customizable actions, multi-action support',
                'price' => 2399000,
                'original_price' => 2699000,
                'stock' => 25,
                'image_url' => 'https://placehold.co/400x400/1A1A1A/FFFFFF?text=Stream+Deck',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 89,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 11,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Blue Yeti X Professional USB Microphone',
                'description' => 'USB microphone dengan 4 polar patterns, LED metering, high-res audio 24-bit/48kHz',
                'price' => 2699000,
                'original_price' => 2999000,
                'stock' => 36,
                'image_url' => 'https://placehold.co/400x400/1E90FF/000000?text=Blue+Yeti',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 107,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 10,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Netgear Nighthawk AX12 WiFi 6 Router AX6000',
                'description' => 'WiFi 6 router premium dengan 12-stream, 6Gbps speed, gaming dashboard, VPN support',
                'price' => 6999000,
                'original_price' => 7999000,
                'stock' => 18,
                'image_url' => 'https://placehold.co/400x400/000000/00C8FF?text=Nighthawk',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 64,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 13,
                'badge' => 'Ekslusif',
                'is_active' => true,
            ],
            [
                'seller_id' => 1,
                'name' => 'Wacom Intuos Pro Large Digital Drawing Tablet',
                'description' => 'Drawing tablet profesional dengan 8192 pressure levels, multi-touch, wireless connectivity',
                'price' => 6499000,
                'original_price' => 7299000,
                'stock' => 16,
                'image_url' => 'https://placehold.co/400x400/2D2D2D/00FF00?text=Wacom+Pro',
                'category' => 'Technology',
                'rating' => 5,
                'sold_count' => 73,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 11,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
        ];

        Product::insert($techProducts);

        $products = [
            [
                'name' => 'Premium Wireless Headphones with Noise Cancellation',
                'description' => 'Headphone wireless premium dengan noise cancellation aktif, baterai tahan hingga 30 jam',
                'price' => 899000,
                'original_price' => 2000000,
                'stock' => 50,
                'image_url' => 'https://placehold.co/200x200/FFD93D/000000?text=Headphone',
                'category' => 'Handphone',
                'rating' => 49,
                'sold_count' => 1200,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 55,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'name' => 'Luxury Smart Watch Series 8 - GPS + Cellular',
                'description' => 'Smartwatch mewah dengan GPS dan Cellular, monitoring kesehatan lengkap',
                'price' => 2499000,
                'original_price' => 3500000,
                'stock' => 30,
                'image_url' => 'https://placehold.co/200x200/E5E5E5/000000?text=Smartwatch',
                'category' => 'Handphone',
                'rating' => 48,
                'sold_count' => 924,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 30,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'name' => 'Designer Sunglasses UV Protection Premium Quality',
                'description' => 'Kacamata hitam designer dengan proteksi UV, lensa polarized',
                'price' => 349000,
                'original_price' => 500000,
                'stock' => 100,
                'image_url' => 'https://placehold.co/200x200/1A1A1A/FFFFFF?text=Sunglasses',
                'category' => 'Fashion Pria',
                'rating' => 47,
                'sold_count' => 715,
                'location' => 'Kab. Bandung',
                'discount_percentage' => 20,
                'badge' => 'Mall',
                'is_active' => true,
            ],
            [
                'name' => 'Premium Running Shoes Lightweight Sport Edition',
                'description' => 'Sepatu lari premium dengan teknologi cushioning terbaru',
                'price' => 799000,
                'original_price' => 1200000,
                'stock' => 75,
                'image_url' => 'https://placehold.co/200x200/2B2B2B/FFFFFF?text=Running+Shoes',
                'category' => 'Fashion Pria',
                'rating' => 49,
                'sold_count' => 781,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 40,
                'badge' => 'Mall',
                'is_active' => true,
            ],
            [
                'name' => 'Vintage Leather Backpack Premium Quality',
                'description' => 'Tas ransel kulit vintage berkualitas tinggi dengan banyak kompartemen',
                'price' => 599000,
                'original_price' => 850000,
                'stock' => 40,
                'image_url' => 'https://placehold.co/200x200/FFB6C1/000000?text=Backpack',
                'category' => 'Tas Selempang Pria',
                'rating' => 48,
                'sold_count' => 284,
                'location' => 'Kota Surabaya',
                'discount_percentage' => 30,
                'badge' => 'Mall',
                'is_active' => true,
            ],
            [
                'name' => 'Professional Camera Lens 50mm f/1.8',
                'description' => 'Lensa kamera profesional dengan aperture besar untuk foto portrait',
                'price' => 1299000,
                'original_price' => 2000000,
                'stock' => 20,
                'image_url' => 'https://placehold.co/200x200/E8E8E8/000000?text=Camera',
                'category' => 'Handphone',
                'rating' => 49,
                'sold_count' => 523,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 35,
                'badge' => 'Mall',
                'is_active' => true,
            ],
            [
                'name' => 'Wireless Gaming Mouse RGB LED',
                'description' => 'Mouse gaming wireless dengan RGB LED, DPI hingga 16000',
                'price' => 450000,
                'original_price' => 750000,
                'stock' => 80,
                'image_url' => 'https://placehold.co/200x200/FF6B6B/000000?text=Gaming+Mouse',
                'category' => 'Handphone',
                'rating' => 48,
                'sold_count' => 1050,
                'location' => 'Kota Bandung',
                'discount_percentage' => 40,
                'badge' => 'Mall',
                'is_active' => true,
            ],
            [
                'name' => 'Mechanical Keyboard RGB Backlight Cherry MX',
                'description' => 'Keyboard mechanical dengan switch Cherry MX dan RGB backlight',
                'price' => 1100000,
                'original_price' => 1500000,
                'stock' => 35,
                'image_url' => 'https://placehold.co/200x200/4ECDC4/000000?text=Keyboard',
                'category' => 'Handphone',
                'rating' => 50,
                'sold_count' => 892,
                'location' => 'Jakarta Barat',
                'discount_percentage' => 27,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'name' => 'Korean Style Oversized Hoodie Premium',
                'description' => 'Hoodie oversized gaya Korea dengan bahan cotton premium',
                'price' => 175000,
                'original_price' => 300000,
                'stock' => 150,
                'image_url' => 'https://placehold.co/200x200/95E1D3/000000?text=Hoodie',
                'category' => 'Fashion Pria',
                'rating' => 47,
                'sold_count' => 2100,
                'location' => 'Kota Surabaya',
                'discount_percentage' => 42,
                'badge' => 'Mall',
                'is_active' => true,
            ],
            [
                'name' => 'Minimalist Leather Wallet RFID Protection',
                'description' => 'Dompet kulit minimalis dengan proteksi RFID untuk keamanan kartu',
                'price' => 250000,
                'original_price' => 400000,
                'stock' => 90,
                'image_url' => 'https://placehold.co/200x200/F38181/000000?text=Wallet',
                'category' => 'Fashion Pria',
                'rating' => 48,
                'sold_count' => 654,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 38,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'name' => 'Flat Shoes Wanita Casual Comfortable',
                'description' => 'Sepatu flat wanita casual yang nyaman untuk aktivitas sehari-hari',
                'price' => 125000,
                'original_price' => 250000,
                'stock' => 200,
                'image_url' => 'https://placehold.co/200x200/AA96DA/FFFFFF?text=Flat+Shoes',
                'category' => 'Flat Shoes Wanita',
                'rating' => 46,
                'sold_count' => 1850,
                'location' => 'Kab. Tangerang',
                'discount_percentage' => 50,
                'badge' => 'Mall',
                'is_active' => true,
            ],
            [
                'name' => 'Makanan Kering Premium Snack Box 500gr',
                'description' => 'Paket snack makanan kering premium dengan berbagai pilihan rasa',
                'price' => 85000,
                'original_price' => 150000,
                'stock' => 300,
                'image_url' => 'https://placehold.co/200x200/FCBAD3/000000?text=Snack+Box',
                'category' => 'Makanan Kering',
                'rating' => 48,
                'sold_count' => 3200,
                'location' => 'Jakarta Timur',
                'discount_percentage' => 43,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'name' => 'Figure Action Hero Collection Limited Edition',
                'description' => 'Figure action hero koleksi terbatas dengan detail sempurna',
                'price' => 550000,
                'original_price' => 800000,
                'stock' => 25,
                'image_url' => 'https://placehold.co/200x200/A8D8EA/000000?text=Figure',
                'category' => 'Figure',
                'rating' => 50,
                'sold_count' => 156,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 31,
                'badge' => 'Mall',
                'is_active' => true,
            ],
            [
                'name' => 'Skincare Set Kecantikan Complete Package',
                'description' => 'Paket lengkap skincare untuk perawatan wajah dengan bahan alami',
                'price' => 299000,
                'original_price' => 500000,
                'stock' => 120,
                'image_url' => 'https://placehold.co/200x200/FFFFD2/000000?text=Skincare',
                'category' => 'Kecantikan',
                'rating' => 49,
                'sold_count' => 1420,
                'location' => 'Kota Bandung',
                'discount_percentage' => 40,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'name' => 'Peralatan Rumah Tangga Set Kitchen Tools',
                'description' => 'Set lengkap peralatan dapur modern untuk memasak sehari-hari',
                'price' => 375000,
                'original_price' => 650000,
                'stock' => 60,
                'image_url' => 'https://placehold.co/200x200/FEC8D8/000000?text=Kitchen+Set',
                'category' => 'Rumah Tangga',
                'rating' => 47,
                'sold_count' => 892,
                'location' => 'Kota Surabaya',
                'discount_percentage' => 42,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            // Produk Baju
            [
                'name' => 'Baju Batik Modern Premium Pria',
                'description' => 'Batik modern dengan motif kontemporer yang elegan',
                'price' => 285000,
                'original_price' => 450000,
                'stock' => 85,
                'image_url' => 'https://placehold.co/200x200/8B4513/FFFFFF?text=Batik',
                'category' => 'Fashion Pria',
                'rating' => 48,
                'sold_count' => 765,
                'location' => 'Solo',
                'discount_percentage' => 37,
                'badge' => 'Mall',
                'is_active' => true,
            ],
            [
                'name' => 'Baju Koko Muslim Putih Premium',
                'description' => 'Baju koko nyaman untuk ibadah dan acara formal',
                'price' => 175000,
                'original_price' => 280000,
                'stock' => 120,
                'image_url' => 'https://placehold.co/200x200/FFFFFF/000000?text=Baju+Koko',
                'category' => 'Fashion Pria',
                'rating' => 47,
                'sold_count' => 1230,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 38,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'name' => 'Baju Kemeja Lengan Pendek Casual',
                'description' => 'Kemeja casual nyaman untuk sehari-hari',
                'price' => 145000,
                'original_price' => 250000,
                'stock' => 95,
                'image_url' => 'https://placehold.co/200x200/4A90E2/FFFFFF?text=Kemeja',
                'category' => 'Fashion Pria',
                'rating' => 46,
                'sold_count' => 654,
                'location' => 'Bandung',
                'discount_percentage' => 42,
                'is_active' => true,
            ],
            // Produk Bantal
            [
                'name' => 'Bantal Tidur Memory Foam Ergonomis',
                'description' => 'Bantal memory foam yang menyesuaikan bentuk kepala',
                'price' => 165000,
                'original_price' => 300000,
                'stock' => 110,
                'image_url' => 'https://placehold.co/200x200/E0E0E0/000000?text=Bantal+Memory',
                'category' => 'Rumah Tangga',
                'rating' => 49,
                'sold_count' => 1450,
                'location' => 'Jakarta Utara',
                'discount_percentage' => 45,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'name' => 'Bantal Guling Set Karakter Lucu',
                'description' => 'Set bantal guling dengan motif karakter menggemaskan',
                'price' => 125000,
                'original_price' => 220000,
                'stock' => 88,
                'image_url' => 'https://placehold.co/200x200/FFB6C1/000000?text=Bantal+Guling',
                'category' => 'Rumah Tangga',
                'rating' => 48,
                'sold_count' => 892,
                'location' => 'Surabaya',
                'discount_percentage' => 43,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'name' => 'Bantal Leher Travel U-Shape Premium',
                'description' => 'Bantal leher bentuk U untuk perjalanan jauh',
                'price' => 85000,
                'original_price' => 150000,
                'stock' => 145,
                'image_url' => 'https://placehold.co/200x200/87CEEB/000000?text=Bantal+Leher',
                'category' => 'Rumah Tangga',
                'rating' => 46,
                'sold_count' => 567,
                'location' => 'Tangerang',
                'discount_percentage' => 43,
                'is_active' => true,
            ],
            [
                'name' => 'Bantal Sofa Dekoratif Warna Warni',
                'description' => 'Bantal dekoratif untuk mempercantik sofa',
                'price' => 65000,
                'original_price' => 120000,
                'stock' => 200,
                'image_url' => 'https://placehold.co/200x200/FF69B4/FFFFFF?text=Bantal+Sofa',
                'category' => 'Rumah Tangga',
                'rating' => 45,
                'sold_count' => 1234,
                'location' => 'Bekasi',
                'discount_percentage' => 46,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            // Tambahan produk untuk Figure
            [
                'name' => 'Figure Anime Character Premium Edition',
                'description' => 'Figure anime karakter premium dengan detail tinggi',
                'price' => 450000,
                'original_price' => 650000,
                'stock' => 30,
                'image_url' => 'https://placehold.co/200x200/FF6B9D/FFFFFF?text=Anime+Figure',
                'category' => 'Figure',
                'rating' => 49,
                'sold_count' => 234,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 31,
                'badge' => 'Ekslusif',
                'is_active' => true,
            ],
            [
                'name' => 'Figure Marvel Superhero Collectible',
                'description' => 'Figure superhero Marvel untuk koleksi',
                'price' => 380000,
                'original_price' => 550000,
                'stock' => 25,
                'image_url' => 'https://placehold.co/200x200/FF4757/FFFFFF?text=Marvel+Figure',
                'category' => 'Figure',
                'rating' => 48,
                'sold_count' => 189,
                'location' => 'Bandung',
                'discount_percentage' => 31,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            // Tambahan produk untuk Flat Shoes Wanita
            [
                'name' => 'Flat Shoes Wanita Kulit Sintetis',
                'description' => 'Sepatu flat wanita dari kulit sintetis berkualitas',
                'price' => 145000,
                'original_price' => 250000,
                'stock' => 180,
                'image_url' => 'https://placehold.co/200x200/FFC0CB/000000?text=Flat+Shoes',
                'category' => 'Flat Shoes Wanita',
                'rating' => 47,
                'sold_count' => 1234,
                'location' => 'Jakarta',
                'discount_percentage' => 42,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'name' => 'Flat Shoes Wanita Slip On Canvas',
                'description' => 'Sepatu flat slip on canvas nyaman untuk aktivitas',
                'price' => 95000,
                'original_price' => 180000,
                'stock' => 220,
                'image_url' => 'https://placehold.co/200x200/E6B0AA/000000?text=Canvas+Shoes',
                'category' => 'Flat Shoes Wanita',
                'rating' => 46,
                'sold_count' => 1876,
                'location' => 'Surabaya',
                'discount_percentage' => 47,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            // Tambahan produk untuk Kecantikan
            [
                'name' => 'Skincare Brightening Serum Vitamin C',
                'description' => 'Serum vitamin C untuk mencerahkan kulit wajah',
                'price' => 185000,
                'original_price' => 320000,
                'stock' => 150,
                'image_url' => 'https://placehold.co/200x200/FFE4E1/000000?text=Serum',
                'category' => 'Kecantikan',
                'rating' => 49,
                'sold_count' => 2345,
                'location' => 'Jakarta',
                'discount_percentage' => 42,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'name' => 'Lipstick Matte Long Lasting Set 5 Colors',
                'description' => 'Set lipstick matte tahan lama 5 warna cantik',
                'price' => 125000,
                'original_price' => 200000,
                'stock' => 200,
                'image_url' => 'https://placehold.co/200x200/DC143C/FFFFFF?text=Lipstick',
                'category' => 'Kecantikan',
                'rating' => 48,
                'sold_count' => 1987,
                'location' => 'Bandung',
                'discount_percentage' => 38,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            // Tambahan produk untuk Handphone
            [
                'name' => 'Smartphone Android 5G 8GB RAM',
                'description' => 'Smartphone android dengan jaringan 5G dan RAM 8GB',
                'price' => 3499000,
                'original_price' => 5000000,
                'stock' => 35,
                'image_url' => 'https://placehold.co/200x200/000000/FFFFFF?text=Smartphone',
                'category' => 'Handphone',
                'rating' => 49,
                'sold_count' => 567,
                'location' => 'Jakarta',
                'discount_percentage' => 30,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            // Tambahan produk untuk Makanan Kering
            [
                'name' => 'Kue Kering Nastar Premium 500gr',
                'description' => 'Kue nastar premium dengan selai nanas asli',
                'price' => 95000,
                'original_price' => 150000,
                'stock' => 250,
                'image_url' => 'https://placehold.co/200x200/FFD700/000000?text=Nastar',
                'category' => 'Makanan Kering',
                'rating' => 48,
                'sold_count' => 3456,
                'location' => 'Bandung',
                'discount_percentage' => 37,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'name' => 'Kerupuk Udang Jumbo Krispi 250gr',
                'description' => 'Kerupuk udang jumbo yang renyah dan gurih',
                'price' => 45000,
                'original_price' => 75000,
                'stock' => 300,
                'image_url' => 'https://placehold.co/200x200/FFA500/000000?text=Kerupuk',
                'category' => 'Makanan Kering',
                'rating' => 47,
                'sold_count' => 4567,
                'location' => 'Surabaya',
                'discount_percentage' => 40,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            // Tambahan produk untuk Tas Selempang Pria
            [
                'name' => 'Tas Selempang Canvas Pria Casual',
                'description' => 'Tas selempang canvas untuk pria dengan banyak kantong',
                'price' => 175000,
                'original_price' => 280000,
                'stock' => 85,
                'image_url' => 'https://placehold.co/200x200/696969/FFFFFF?text=Canvas+Bag',
                'category' => 'Tas Selempang Pria',
                'rating' => 47,
                'sold_count' => 543,
                'location' => 'Jakarta',
                'discount_percentage' => 38,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'name' => 'Tas Selempang Outdoor Waterproof',
                'description' => 'Tas selempang anti air untuk aktivitas outdoor',
                'price' => 225000,
                'original_price' => 350000,
                'stock' => 65,
                'image_url' => 'https://placehold.co/200x200/2F4F4F/FFFFFF?text=Outdoor+Bag',
                'category' => 'Tas Selempang Pria',
                'rating' => 48,
                'sold_count' => 432,
                'location' => 'Bandung',
                'discount_percentage' => 36,
                'is_active' => true,
            ],
            // Tambahan produk untuk Rumah Tangga
            [
                'name' => 'Set Peralatan Makan Keramik 24 Pieces',
                'description' => 'Set lengkap peralatan makan keramik untuk 6 orang',
                'price' => 385000,
                'original_price' => 650000,
                'stock' => 45,
                'image_url' => 'https://placehold.co/200x200/E0E0E0/000000?text=Dinnerware',
                'category' => 'Rumah Tangga',
                'rating' => 48,
                'sold_count' => 456,
                'location' => 'Surabaya',
                'discount_percentage' => 41,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'name' => 'Dispenser Air Galon Bawah Premium',
                'description' => 'Dispenser air dengan galon bawah, hemat tempat',
                'price' => 850000,
                'original_price' => 1200000,
                'stock' => 25,
                'image_url' => 'https://placehold.co/200x200/4682B4/FFFFFF?text=Dispenser',
                'category' => 'Rumah Tangga',
                'rating' => 49,
                'sold_count' => 234,
                'location' => 'Jakarta',
                'discount_percentage' => 29,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
