<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Premium Wireless Headphones with Noise Cancellation',
                'description' => 'Headphone wireless premium dengan noise cancellation aktif, baterai tahan hingga 30 jam',
                'price' => 899000,
                'original_price' => 2000000,
                'stock' => 50,
                'image_url' => 'https://via.placeholder.com/200x200/FFD93D/000000?text=Headphone',
                'category' => 'Handphone',
                'rating' => 49,
                'sold_count' => 1200,
                'location' => 'Kab. Jakarta',
                'discount_percentage' => 55,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'name' => 'Luxury Smart Watch Series 8 - GPS + Cellular',
                'description' => 'Smartwatch mewah dengan GPS dan Cellular, monitoring kesehatan lengkap',
                'price' => 2499000,
                'original_price' => 3500000,
                'stock' => 30,
                'image_url' => 'https://via.placeholder.com/200x200/E5E5E5/000000?text=Smartwatch',
                'category' => 'Handphone',
                'rating' => 48,
                'sold_count' => 924,
                'location' => 'Kota Jakarta',
                'discount_percentage' => 30,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'name' => 'Designer Sunglasses UV Protection Premium Quality',
                'description' => 'Kacamata hitam designer dengan proteksi UV, lensa polarized',
                'price' => 349000,
                'original_price' => 500000,
                'stock' => 100,
                'image_url' => 'https://via.placeholder.com/200x200/1A1A1A/FFFFFF?text=Sunglasses',
                'category' => 'Fashion Pria',
                'rating' => 47,
                'sold_count' => 715,
                'location' => 'Kab. Bandung',
                'discount_percentage' => 20,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'name' => 'Premium Running Shoes Lightweight Sport Edition',
                'description' => 'Sepatu lari premium dengan teknologi cushioning terbaru',
                'price' => 799000,
                'original_price' => 1200000,
                'stock' => 75,
                'image_url' => 'https://via.placeholder.com/200x200/2B2B2B/FFFFFF?text=Running+Shoes',
                'category' => 'Fashion Pria',
                'rating' => 49,
                'sold_count' => 781,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 40,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'name' => 'Vintage Leather Backpack Premium Quality',
                'description' => 'Tas ransel kulit vintage berkualitas tinggi dengan banyak kompartemen',
                'price' => 599000,
                'original_price' => 850000,
                'stock' => 40,
                'image_url' => 'https://via.placeholder.com/200x200/FFB6C1/000000?text=Backpack',
                'category' => 'Tas Selempang Pria',
                'rating' => 48,
                'sold_count' => 284,
                'location' => 'Kota Surabaya',
                'discount_percentage' => 30,
                'badge' => 'Ekslusif',
                'is_active' => true,
            ],
            [
                'name' => 'Professional Camera Lens 50mm f/1.8',
                'description' => 'Lensa kamera profesional dengan aperture besar untuk foto portrait',
                'price' => 1299000,
                'original_price' => 2000000,
                'stock' => 20,
                'image_url' => 'https://via.placeholder.com/200x200/E8E8E8/000000?text=Camera',
                'category' => 'Handphone',
                'rating' => 49,
                'sold_count' => 523,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 35,
                'badge' => 'Ekslusif',
                'is_active' => true,
            ],
            [
                'name' => 'Wireless Gaming Mouse RGB LED',
                'description' => 'Mouse gaming wireless dengan RGB LED, DPI hingga 16000',
                'price' => 450000,
                'original_price' => 750000,
                'stock' => 80,
                'image_url' => 'https://via.placeholder.com/200x200/FF6B6B/000000?text=Gaming+Mouse',
                'category' => 'Handphone',
                'rating' => 48,
                'sold_count' => 1050,
                'location' => 'Kota Bandung',
                'discount_percentage' => 40,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'name' => 'Mechanical Keyboard RGB Backlight Cherry MX',
                'description' => 'Keyboard mechanical dengan switch Cherry MX dan RGB backlight',
                'price' => 1100000,
                'original_price' => 1500000,
                'stock' => 35,
                'image_url' => 'https://via.placeholder.com/200x200/4ECDC4/000000?text=Keyboard',
                'category' => 'Handphone',
                'rating' => 50,
                'sold_count' => 892,
                'location' => 'Jakarta Barat',
                'discount_percentage' => 27,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'name' => 'Korean Style Oversized Hoodie Premium',
                'description' => 'Hoodie oversized gaya Korea dengan bahan cotton premium',
                'price' => 175000,
                'original_price' => 300000,
                'stock' => 150,
                'image_url' => 'https://via.placeholder.com/200x200/95E1D3/000000?text=Hoodie',
                'category' => 'Fashion Pria',
                'rating' => 47,
                'sold_count' => 2100,
                'location' => 'Kota Surabaya',
                'discount_percentage' => 42,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'name' => 'Minimalist Leather Wallet RFID Protection',
                'description' => 'Dompet kulit minimalis dengan proteksi RFID untuk keamanan kartu',
                'price' => 250000,
                'original_price' => 400000,
                'stock' => 90,
                'image_url' => 'https://via.placeholder.com/200x200/F38181/000000?text=Wallet',
                'category' => 'Fashion Pria',
                'rating' => 48,
                'sold_count' => 654,
                'location' => 'Jakarta Selatan',
                'discount_percentage' => 38,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'name' => 'Flat Shoes Wanita Casual Comfortable',
                'description' => 'Sepatu flat wanita casual yang nyaman untuk aktivitas sehari-hari',
                'price' => 125000,
                'original_price' => 250000,
                'stock' => 200,
                'image_url' => 'https://via.placeholder.com/200x200/AA96DA/FFFFFF?text=Flat+Shoes',
                'category' => 'Flat Shoes Wanita',
                'rating' => 46,
                'sold_count' => 1850,
                'location' => 'Kab. Tangerang',
                'discount_percentage' => 50,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'name' => 'Makanan Kering Premium Snack Box 500gr',
                'description' => 'Paket snack makanan kering premium dengan berbagai pilihan rasa',
                'price' => 85000,
                'original_price' => 150000,
                'stock' => 300,
                'image_url' => 'https://via.placeholder.com/200x200/FCBAD3/000000?text=Snack+Box',
                'category' => 'Makanan Kering',
                'rating' => 48,
                'sold_count' => 3200,
                'location' => 'Kota Jakarta',
                'discount_percentage' => 43,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'name' => 'Figure Action Hero Collection Limited Edition',
                'description' => 'Figure action hero koleksi terbatas dengan detail sempurna',
                'price' => 550000,
                'original_price' => 800000,
                'stock' => 25,
                'image_url' => 'https://via.placeholder.com/200x200/A8D8EA/000000?text=Figure',
                'category' => 'Figure',
                'rating' => 50,
                'sold_count' => 156,
                'location' => 'Jakarta Pusat',
                'discount_percentage' => 31,
                'badge' => 'Ekslusif',
                'is_active' => true,
            ],
            [
                'name' => 'Skincare Set Kecantikan Complete Package',
                'description' => 'Paket lengkap skincare untuk perawatan wajah dengan bahan alami',
                'price' => 299000,
                'original_price' => 500000,
                'stock' => 120,
                'image_url' => 'https://via.placeholder.com/200x200/FFFFD2/000000?text=Skincare',
                'category' => 'Kecantikan',
                'rating' => 49,
                'sold_count' => 1420,
                'location' => 'Kota Bandung',
                'discount_percentage' => 40,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'name' => 'Peralatan Rumah Tangga Set Kitchen Tools',
                'description' => 'Set lengkap peralatan dapur modern untuk memasak sehari-hari',
                'price' => 375000,
                'original_price' => 650000,
                'stock' => 60,
                'image_url' => 'https://via.placeholder.com/200x200/FEC8D8/000000?text=Kitchen+Set',
                'category' => 'Rumah Tangga',
                'rating' => 47,
                'sold_count' => 892,
                'location' => 'Kota Surabaya',
                'discount_percentage' => 42,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            // Produk Baju
            [
                'name' => 'Baju Batik Modern Premium Pria',
                'description' => 'Batik modern dengan motif kontemporer yang elegan',
                'price' => 285000,
                'original_price' => 450000,
                'stock' => 85,
                'image_url' => 'https://via.placeholder.com/200x200/8B4513/FFFFFF?text=Batik',
                'category' => 'Fashion Pria',
                'rating' => 48,
                'sold_count' => 765,
                'location' => 'Solo',
                'discount_percentage' => 37,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'name' => 'Baju Koko Muslim Putih Premium',
                'description' => 'Baju koko nyaman untuk ibadah dan acara formal',
                'price' => 175000,
                'original_price' => 280000,
                'stock' => 120,
                'image_url' => 'https://via.placeholder.com/200x200/FFFFFF/000000?text=Baju+Koko',
                'category' => 'Fashion Pria',
                'rating' => 47,
                'sold_count' => 1230,
                'location' => 'Jakarta',
                'discount_percentage' => 38,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'name' => 'Baju Kemeja Lengan Pendek Casual',
                'description' => 'Kemeja casual nyaman untuk sehari-hari',
                'price' => 145000,
                'original_price' => 250000,
                'stock' => 95,
                'image_url' => 'https://via.placeholder.com/200x200/4A90E2/FFFFFF?text=Kemeja',
                'category' => 'Fashion Pria',
                'rating' => 46,
                'sold_count' => 654,
                'location' => 'Bandung',
                'discount_percentage' => 42,
                'is_active' => true,
            ],
            // Produk Bantal
            [
                'name' => 'Bantal Tidur Memory Foam Ergonomis',
                'description' => 'Bantal memory foam yang menyesuaikan bentuk kepala',
                'price' => 165000,
                'original_price' => 300000,
                'stock' => 110,
                'image_url' => 'https://via.placeholder.com/200x200/E0E0E0/000000?text=Bantal+Memory',
                'category' => 'Rumah Tangga',
                'rating' => 49,
                'sold_count' => 1450,
                'location' => 'Jakarta',
                'discount_percentage' => 45,
                'badge' => 'Best Seller',
                'is_active' => true,
            ],
            [
                'name' => 'Bantal Guling Set Karakter Lucu',
                'description' => 'Set bantal guling dengan motif karakter menggemaskan',
                'price' => 125000,
                'original_price' => 220000,
                'stock' => 88,
                'image_url' => 'https://via.placeholder.com/200x200/FFB6C1/000000?text=Bantal+Guling',
                'category' => 'Rumah Tangga',
                'rating' => 48,
                'sold_count' => 892,
                'location' => 'Surabaya',
                'discount_percentage' => 43,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
            [
                'name' => 'Bantal Leher Travel U-Shape Premium',
                'description' => 'Bantal leher bentuk U untuk perjalanan jauh',
                'price' => 85000,
                'original_price' => 150000,
                'stock' => 145,
                'image_url' => 'https://via.placeholder.com/200x200/87CEEB/000000?text=Bantal+Leher',
                'category' => 'Rumah Tangga',
                'rating' => 46,
                'sold_count' => 567,
                'location' => 'Tangerang',
                'discount_percentage' => 43,
                'is_active' => true,
            ],
            [
                'name' => 'Bantal Sofa Dekoratif Warna Warni',
                'description' => 'Bantal dekoratif untuk mempercantik sofa',
                'price' => 65000,
                'original_price' => 120000,
                'stock' => 200,
                'image_url' => 'https://via.placeholder.com/200x200/FF69B4/FFFFFF?text=Bantal+Sofa',
                'category' => 'Rumah Tangga',
                'rating' => 45,
                'sold_count' => 1234,
                'location' => 'Bekasi',
                'discount_percentage' => 46,
                'badge' => 'Terkirim cepat',
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
